name: Build

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.14
      - name: Format Check📋✅
        run: sbt 'fmtCheck'
      - name: Compile 🛠️📦
        run: sbt 'compile'